name: Build with Clang

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.h'
jobs:  
  build:
    name: 'build on Haiku with Clang'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/hectorm/qemu-haiku:latest'
    steps:
    - name: 'Wait until the VM is ready'
      run: 'container-init & timeout 600 vmshell exit 0'
    - name: 'Install packages'
      run: 'vmshell pkgman install -y gcc haiku_devel make makefile_engine llvm17_clang llvm17_lld libgit2_devel lexilla_devel yaml_cpp*_devel editorconfig_core_c_devel'
    - name: 'Checkout project'
      uses: actions/checkout@v4
    - name: 'Copy project to VM'
      run: 'vmshell mkdir ./src/; tar -cf - ./ | vmshell tar -xf - -C ./src/'
    - name: 'Build project'
      run: 'vmshell make BUILD_WITH_CLANG=1 BUILDHOME=\`finddir B_SYSTEM_DEVELOP_DIRECTORY\` -C ./src/'
