name: "haiku-ci-clang"

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.h'
      - '**.rdef'
      - 'Makefile'
  pull_request:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.h'
      - '**.rdef'
      - 'Makefile'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-haiku:
    timeout-minutes: 60
    runs-on: ${{ matrix.config.runner }}
    name: build-${{ matrix.config.os }}-${{ matrix.config.version }}-${{ matrix.config.architecture }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # The OS versions supported are specific to the version of the action
          # https://github.com/cross-platform-actions/action/blob/master/changelog.md
          - { os: haiku, version: 'r1beta5', runner: 'ubuntu-latest', architecture: 'x86-64' }
          
    steps:
      - uses: actions/checkout@v4

      - uses: korli/action@v0.25.0-haiku3
        with:
          operating_system: ${{ matrix.config.os }}
          version: ${{ matrix.config.version }}
          architecture: ${{ matrix.config.architecture }}
          run: |
            ssh user@localhost "pkgman update -y haiku_devel cmd:gcc gcc_syslibs_devel llvm17_clang llvm17_lld libgit2_1.8_devel lexilla_devel yaml_cpp*_devel editorconfig_core_c_devel" &&
            make BUILD_WITH_CLANG=1 
